version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_assignees:
      - growse
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "daily"
    default_assignees:
      - growse
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"