name: Build, package and upload
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Build
        run: make build
      - name: Test
        run: make test
      - name: Upload to codecov
        run: bash <(curl -s https://codecov.io/bash)
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Install gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Package
        run: make package
        env:
          BUILD_NUMBER: ${{ github.run_number }}
      - name: Upload to S3 Apt repo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEBSIGN: ${{ secrets.DEBSIGN }}
          BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
        run: |
          echo 'aaaaaaaa' > passphrase_file
          echo $DEBSIGN | base64 -d | gpg --import --batch
          gpg --list-secret-keys
          bundle exec deb-s3 upload --s3-region=eu-north-1 --sign=6A2561804E290210909454E69640EFFBAA3B94A5 --gpg-options="\-\-pinentry\-mode=loopback \-\-passphrase\-file passphrase_file \-\-batch" --suite stable --origin "Andrew Rowson" --bucket apt.growse.com "*.deb"
